import Image from "next/image";
import Link from "next/link";
import pregnancyImage from "@/public/image/pregnancy-diet-img1.jpg";
import { ServiceCtaButtons } from "@/app/components/ServiceCtaButtons";
import { PregnancyDietSections } from "./PregnancyDietSections";

const faqs = [
  ["Can nutrition support replace prenatal medical care?", "No. Nutrition guidance does not replace antenatal appointments, medical advice, prescribed supplements, tests or treatment from your obstetrician or treating clinician."],
  ["What can I discuss in a pregnancy nutrition consultation?", "You can discuss everyday meals, food preferences, appetite changes, meal planning and questions about nutrition. Your clinician should advise you on medical symptoms, supplements, medications, pregnancy complications and individual medical restrictions."],
  ["Can I ask about postpartum or breastfeeding nutrition?", "Yes. You can ask about practical food routines for the postpartum period and breastfeeding. Continue to seek medical or lactation support for health concerns affecting you or your baby."],
  ["When should I contact my doctor urgently?", "Contact your obstetrician, maternity unit or emergency services for urgent symptoms or concerns. This service is not designed for urgent care."],
];

export default function PregnancyDietProgram() {
    <section className="bg-gradient-to-br from-rose-950 via-fuchsia-800 to-purple-700 px-4 py-16 text-white md:py-24"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="mb-4 font-semibold uppercase tracking-[.18em] text-rose-100 text-sm">Mumbai, Thane & online across India</p><h1 className="text-4xl font-bold tracking-tight md:text-6xl">Practical pregnancy nutrition support alongside antenatal care</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-rose-50 md:text-xl">Pregnancy brings changing routines, food preferences and many questions. DietFiniti offers personalised nutrition guidance to help you plan everyday meals while you continue receiving care and medical advice from your obstetrician or treating clinician.</p><div className="mt-9"><ServiceCtaButtons contactColorClass="text-fuchsia-800" /></div></div><aside className="rounded-2xl border border-white/20 bg-white/10 p-7 backdrop-blur-sm"><h2 className="text-2xl font-bold">Your clinical care comes first</h2><ul className="mt-5 space-y-4 leading-7 text-rose-50"><li>• Keep all antenatal appointments and follow your clinician’s advice.</li><li>• Do not change prescribed supplements or medication without medical advice.</li><li>• Contact your maternity team for symptoms or concerns—not this website.</li><li>• Nutrition support can complement, not replace, pregnancy care.</li></ul></aside></div></section>
    <main><section className="mx-auto grid max-w-6xl gap-10 px-4 py-16 md:grid-cols-2 md:items-center md:py-20"><div><p className="font-semibold text-fuchsia-700">Personalised food planning</p><h2 className="mt-3 text-3xl font-bold text-slate-900 md:text-4xl">Support for real meals, changing routines and your questions</h2><p className="mt-5 leading-8 text-slate-700">There is no one pregnancy meal plan that fits everyone. A consultation can be a place to talk through your preferences, daily schedule, appetite, cooking access and questions about planning balanced meals.</p><p className="mt-4 leading-8 text-slate-700">If you have a medical condition, pregnancy complication, severe nausea or vomiting, food allergy, or have been given a therapeutic diet, follow your doctor’s advice and ask them what nutrition support is appropriate.</p></div><Image src={pregnancyImage} alt="Pregnant person preparing a balanced meal for everyday nutrition planning" className="h-auto w-full rounded-2xl shadow-lg" /></section>
    <section className="bg-rose-50 px-4 py-16 md:py-20"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-bold text-slate-900">How a consultation can support you</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[["Discuss your routine", "Share what eating looks like in your day, including preferences, work, travel and cooking arrangements."],["Plan practical meals", "Explore meal ideas and habits that are realistic for your circumstances and compatible with clinical advice."],["Prepare questions", "Identify nutrition questions to take to your obstetrician, maternity team or other treating clinician."]].map(([title,text])=><article key={title} className="rounded-xl bg-white p-6 shadow-sm ring-1 ring-rose-100"><h3 className="text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 leading-7 text-slate-700">{text}</p></article>)}</div></div></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-4 py-16 md:grid-cols-2 md:py-20"><div><h2 className="text-3xl font-bold text-slate-900">Postpartum and breastfeeding questions</h2><p className="mt-5 leading-8 text-slate-700">You may also ask about practical meal planning after birth and while breastfeeding. For concerns about your recovery, milk supply, your baby’s feeding, medication or symptoms, contact your obstetrician, paediatrician or qualified lactation professional.</p></div><div className="rounded-2xl bg-fuchsia-50 p-7 ring-1 ring-fuchsia-100"><h2 className="text-2xl font-bold text-slate-900">Speak with DietFiniti</h2><p className="mt-4 leading-7 text-slate-700">Ask about a consultation in Mumbai or Thane, or online from elsewhere in India. The team can explain availability and the information helpful for a nutrition conversation.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/contact" className="rounded-lg bg-fuchsia-700 px-5 py-3 font-semibold text-white hover:bg-fuchsia-800">Contact DietFiniti</Link><Link href="/online-dietitian-consultation" className="rounded-lg border border-fuchsia-700 px-5 py-3 font-semibold text-fuchsia-800 hover:bg-fuchsia-50">Online consultations</Link></div></div></section>
    <PregnancyDietSections /><section className="bg-rose-50 px-4 py-16 md:py-20"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-bold text-slate-900">Pregnancy nutrition FAQs</h2><div className="mt-7 divide-y divide-rose-100 rounded-xl border border-rose-100 bg-white">{faqs.map(([q,a])=><details open key={q} className="group p-5"><summary className="cursor-pointer list-none pr-8 font-semibold text-slate-900">{q}<span className="float-right text-fuchsia-700 group-open:rotate-45">+</span></summary><p className="mt-4 leading-7 text-slate-700">{a}</p></details>)}</div></div></section></main>
  </div>;
}
